# app.post('/moveItems', (req: Request, res: Response) => {
#   const itemMoves: ItemMoves = req.body;

#   appWs.getWss().clients.forEach((client) => {
#     const message: MessageS2CMoveItems = {
#       type: MessageTypeServerToComputer.MOVE_ITEMS,
#       data: itemMoves,
#     };

#     client.send(JSON.stringify(message));
#   });

#   res.json({ message: 'Sent move items to all clients' });
# });

# export interface ItemMove {
#   /** storage name */
#   from: string;
#   /** storage name */
#   to: string;

#   fromSlot: number;
#   toSlot: number | null;
# }

# export interface ItemMoves {
#   moves: ItemMove[];
# # }
GET http://localhost:3000/fetchUpdate HTTP/1.1





POST http://localhost:3000/moveItems HTTP/1.1
Content-Type: application/json

{
  "moves": [
    {
      "from": "minecraft:chest_1",
      "to": "storagedrawers:controller_slave_0",
      "fromSlot": 4,
      "toSlot": null
    }
  ]
}